
apiVersion: apps/v1
kind: Deployment
metadata:
  name: warden
  labels:
    app: warden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warden
  template:
    metadata:
      labels:
        app: warden
    spec:
      containers:
      - name: warden-operator
        image: warden
